name: example
description: Survey example.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  survey_sdk:
    path: ../../core
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.4.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^4.0.0

flutter:
  generate: true
  assets:
    - assets/questions.json

  uses-material-design: true
